"""add riding fields

Revision ID: 19d6d9469f2c
Revises: 6a9640be1356
Create Date: 2026-03-20 02:01:41.232642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d6d9469f2c'
down_revision: Union[str, Sequence[str], None] = '6a9640be1356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('riding_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rooms', sa.Column('riding_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('turns', sa.Column('inherited_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('turns', sa.Column('inherited_dice', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'inherited_dice')
    op.drop_column('turns', 'inherited_score')
    op.drop_column('rooms', 'riding_enabled')
    op.drop_column('games', 'riding_enabled')
    # ### end Alembic commands ###
